export type Language = "PT" | "EN" | "ES" | "FR";

export const translations = {
  PT: {
    navbar: {
      work: "Trabalhos",
      about: "Sobre",
      services: "Serviços",
      contact: "Contato",
      blog: "Notícias",
    },
    seo: {
      title: "Matthew Pinho | Fotografia de Esportes e Eventos",
      description: "Capturando a alta performance e a narrativa atlética em toda a Europa. Especialista em fotografia esportiva e eventos comerciais.",
    },
    hero: {
      titlePart1: "Capturando o",
      titlePart2: "Momento",
      titlePart3: "dentro do movimento",
      subtitle: "Poesia visual através de uma lente cinematográfica. Especializado em fotografia de alto nível e captura dinâmica de movimento.",
      portfolioBtn: "Ver Portfólio",
      workBtn: "Trabalhe comigo",
      scroll: "Rolar",
    },
    about: {
      badge: "Quem Sou & Missão",
      title: "Matthew Pinho: A Perspectiva de um Atleta através das Lentes.",
      bio1: "Mais do que um fotógrafo, sou um",
      bio1Bold: "atleta que vive a pulsação do desporto",
      bio1End: ". Juntei o útil ao agradável para capturar a essência da performance.",
      bio2Part1: "O meu trabalho foca-se em criar",
      bio2Bold: "memórias imortais",
      bio2Part2: "para atletas e adeptos, documentando o suor, a glória e o movimento que definem a carreira de um desportista.",
      quote: "Com base em Portugal, atuo em toda a Europa, com foco especial em Portugal, Suíça, Inglaterra, França, Espanha e Itália.",
      quoteEnd: "Onde houver alta performance, estarei presente.",
      specialization: "Especializações",
      cta: "VAMOS CRIAR A SUA PRÓXIMA MEMÓRIA?",
      badges: ["Fotógrafo de Eventos", "Fotografia Esportiva", "Criador de Conteúdo", "Social Media", "Marketing Esportivo", "Música ao Vivo"],
    },
    services: {
      title: "Fotografia de Esportes e Eventos",
      location: "Sediada em Portugal | Disponível para viagens.",
      desc: "Fotografia comercial de alto impacto. Focada em registrar e imortalizar os momentos decisivos da ação técnica e da euforia humana, entregando poder e narrativa para a sua marca ou equipe.",
      forWhom: "Para quem é indicado",
      features: "Serviços",
      deliveries: "Entregáveis típicos",
      prices: "Tarifas iniciais",
      cta: "Solicitar cobertura",
      globalCta: "ENTRE EM CONTATO COMIGO PARA FALAR SOBRE O SEU PROJETO",
      items: [
        {
          title: "Fotografia Esportiva",
          forWhom: ["Veículos de comunicação", "Ligas esportivas", "Atletas individuais"],
          features: ["Cobertura em tempo real", "Licenciamento de mídia"],
          deliverables: ["Galeria digital", "Fotos curadas para social"],
          price: "€200 - €400",
        },
        {
          title: "Fotografia de Eventos",
          forWhom: ["Eventos Corporativos", "Galas de Premiação", "Conferências"],
          features: ["Documentação completa", "Fotos institucionais"],
          deliverables: ["Galeria de PR (Relações Públicas)", "Arquivos de alta resolução"],
          price: "€400 (2h) - €1.200 (dia inteiro)",
        },
        {
          title: "Trabalhos Editoriais",
          forWhom: ["Revistas e Mídia", "Matérias sobre atletas"],
          features: ["Cobertura fotojornalística", "Retratos direcionados"],
          deliverables: ["Ensaio editorial fotográfico", "Pacote de licenciamento longo"],
          price: "Sob consulta",
        },
        {
          title: "Cobertura de Torneios",
          forWhom: ["Equipes esportivas", "Organizações de Torneios"],
          features: ["Cobertura de vários campos", "Volume fotográfico massivo"],
          deliverables: ["Galeria enorme para download", "Acesso a todos os atletas"],
          price: "€400 - €1.200",
        },
      ],
    },
    contact: {
      title: "Vamos Criar Juntos",
      subtitle: "Seja para uma cobertura explosiva de eventos ou retratos meticulosos, minha lente está pronta para contar sua história.",
      inquireTitle: "Consultar",
      inquireSub: "Preencha os detalhes abaixo e entrarei em contato em até 48 horas.",
      form: {
        name: "Seu Nome *",
        email: "Endereço de Email *",
        date: "Data do Evento ou Localização",
        message: "Conte-me sobre o seu projeto *",
        send: "Enviar Pedido",
        successTitle: "Mensagem Enviada",
        successDesc: "Obrigado por entrar em contato. Retornarei em breve para discutirmos sua visão.",
        another: "Enviar outra mensagem",
      },
      services: [
        { title: "Cobertura de Eventos", desc: "Capturando o calor, a emoção bruta e cada momento irrepetível dos seus eventos ao vivo com ângulos cinematográficos impressionantes." },
        { title: "Retratos de Atletas", desc: "Retratos íntimos e poderosos em estúdio ou locação que destacam a resiliência, dedicação e personalidade do atleta." },
        { title: "Comercial & Marca", desc: "Fotografia institucional e publicitária de alto nível adaptada para elevar a narrativa da sua marca e presença no mercado." },
      ],
    },
    blog: {
      title: "World Sports Hub",
      subtitle: "Onde a performance encontra a informação.",
      categories: {
        football: "Futebol",
        motorsport: "Motorsport",
        bouncing: "Bouncing & Action",
        mind: "Mind Sports",
      },
      filters: {
        all: "Todos",
        men: "Masculino",
        women: "Feminino",
        f1: "Fórmula 1",
        nba: "NBA",
        poker: "Poker",
      },
      rankings: {
        title: "World Rankings & Highlights",
        desc: "Destaque para as principais classificações mundiais.",
      },
      readMore: "Ler notícia completa",
      aggregated: "Notícias agregadas automaticamente dos principais portais desportivos mundiais.",
      loading: "Carregando feed...",
      noNews: "Nenhuma notícia encontrada para esta categoria.",
      source: "Fonte",
    },
    footer: {
      bio: "Fotografia de alto impacto capturando os momentos decisivos no esporte, na ação e no palco comercial.",
      links: "Links Rápidos",
      social: "Social",
      devBy: "Desenvolvido por",
      copy: "Todos os direitos reservados",
    },
    modal: {
      title: "Selecionar Idioma",
      desc: "Escolha o seu idioma preferido para continuar explorando o portfólio.",
    },
    ui: {
      language: "Idioma",
      theme: "Tema",
    }
  },
  EN: {
    navbar: { work: "Work", about: "About", services: "Services", contact: "Contact", blog: "News" },
    seo: {
      title: "Matthew Pinho | Sports & Events Photography",
      description: "Capturing peak performance and athletic storytelling across Europe. Specialist in sports and commercial event photography.",
    },
    hero: {
      titlePart1: "Capturing the",
      titlePart2: "Moment",
      titlePart3: "within the motion",
      subtitle: "Visual poetry through a cinematic lens. Specializing in high-end photography and dynamic motion capture.",
      portfolioBtn: "View Portfolio",
      workBtn: "Work with Me",
      scroll: "Scroll",
    },
    about: {
      badge: "Who I Am & Mission",
      title: "Matthew Pinho: An Athlete's Perspective through the Lens.",
      bio1: "More than a photographer, I am an",
      bio1Bold: "athlete who lives for the sports pulse",
      bio1End: ". I've combined passion with skill to capture the essence of performance.",
      bio2Part1: "My work focuses on creating",
      bio2Bold: "eternal memories",
      bio2Part2: "for athletes and fans, documenting the sweat, the glory, and the movement that define a sport career.",
      quote: "Based in Portugal, I work across Europe, specializing in Portugal, Switzerland, UK, France, Spain and Italy.",
      quoteEnd: "Wherever there is high performance, I will be there.",
      specialization: "Specializations",
      cta: "LET'S CREATE YOUR NEXT MEMORY?",
      badges: ["Events Photographer", "Sports Photography", "Content Creator", "Social Media", "Sports Marketing", "Live Music"],
    },
    services: {
      title: "Sports & Events Photography",
      location: "Based in Portugal | Available for travel.",
      desc: "High-impact commercial photography. Focused on capturing and eternalizing the decisive moments of action and human euphoria, delivering power and narrative to your brand or team.",
      forWhom: "Target Audience",
      features: "Services",
      deliveries: "Typical Deliverables",
      prices: "Starting Rates",
      cta: "Request Coverage",
      globalCta: "GET IN TOUCH TO DISCUSS YOUR PROJECT",
      items: [
        { title: "Sports Photography", forWhom: ["Media outlets", "Sports leagues", "Individual athletes"], features: ["Real-time coverage", "Media licensing"], deliverables: ["Digital gallery", "Curated social photos"], price: "€200 - €400" },
        { title: "Events Photography", forWhom: ["Corporate Events", "Award Galas", "Conferences"], features: ["Full documentation", "Institutional photos"], deliverables: ["PR Gallery", "High-res files"], price: "€400 (2h) - €1,200 (full day)" },
        { title: "Editorial Work", forWhom: ["Magazines & Media", "Athlete features"], features: ["Photojournalistic coverage", "Directed portraits"], deliverables: ["Editorial photoshoot", "Long-term licensing"], price: "On request" },
        { title: "Tournament Coverage", forWhom: ["Sports teams", "Tournament organizers"], features: ["Multi-field coverage", "Massive photo volume"], deliverables: ["Large download gallery", "Athlete access"], price: "€400 - €1,200" },
      ],
    },
    contact: {
      title: "Let's Create Together",
      subtitle: "Whether you need explosive event coverage or meticulous portraiture, my lens is ready to capture your story.",
      inquireTitle: "Inquire",
      inquireSub: "Fill out the details below and I'll get back to you within 48 hours.",
      form: {
        name: "Your Name *",
        email: "Email Address *",
        date: "Event Date or Location",
        message: "Tell me about your project *",
        send: "Send Request",
        successTitle: "Message Sent",
        successDesc: "Thank you for reaching out. I'll get back to you shortly to discuss your vision.",
        another: "Send another message",
      },
      services: [
        { title: "Event Coverage", desc: "Capturing the heat, raw emotion, and unrepeatable moments of your live events with striking cinematic angles." },
        { title: "Athlete Portraits", desc: "Intimate and powerful studio or on-location portraits highlighting the athlete's resilience and personality." },
        { title: "Commercial & Brand", desc: "High-end institutional and advertising photography tailored to elevate your brand's narrative." },
      ],
    },
    blog: {
      title: "World Sports Hub",
      subtitle: "Where performance meets information.",
      categories: {
        football: "Football",
        motorsport: "Motorsport",
        bouncing: "Bouncing & Action",
        mind: "Mind Sports",
      },
      filters: {
        all: "All",
        men: "Men's",
        women: "Women's",
        f1: "Formula 1",
        nba: "NBA",
        poker: "Poker",
      },
      rankings: {
        title: "World Rankings & Highlights",
        desc: "Key standings from global championships.",
      },
      readMore: "Read full story",
      aggregated: "News automatically aggregated from leading global sports portals.",
      loading: "Loading feed...",
      noNews: "No news found for this category.",
      source: "Source",
    },
    footer: {
      bio: "High-impact photography capturing decisive moments in sports, action, and the commercial stage.",
      links: "Quick Links",
      social: "Social",
      devBy: "Developed by",
      copy: "All rights reserved",
    },
    modal: {
      title: "Select Language",
      desc: "Choose your preferred language to continue exploring the portfolio.",
    },
    ui: {
      language: "Language",
      theme: "Theme",
    }
  },
  ES: {
    navbar: { work: "Trabajos", about: "Sobre", services: "Servicios", contact: "Contacto", blog: "Noticias" },
    seo: {
      title: "Matthew Pinho | Fotografía de Deportes y Eventos",
      description: "Capturando el alto rendimiento y la narrativa atlética en toda Europa. Especialista en fotografía deportiva y eventos comerciales.",
    },
    hero: {
      titlePart1: "Capturando el",
      titlePart2: "Momento",
      titlePart3: "dentro del movimiento",
      subtitle: "Poesía visual a través de una lente cinematográfica. Especializado en fotografía de alto nivel e captación dinámica de movimiento.",
      portfolioBtn: "Ver Portafolio",
      workBtn: "Trabaja conmigo",
      scroll: "Desplazar",
    },
    about: {
      badge: "Quién Soy & Misión",
      title: "Matthew Pinho: La Perspectiva de un Atleta a través de las Lentes.",
      bio1: "Más que un fotógrafo, soy un",
      bio1Bold: "atleta que vive el pulso del deporte",
      bio1End: ". He combinado pasión con habilidad para capturar la esencia del rendimiento.",
      bio2Part1: "Mi trabajo se enfoca en crear",
      bio2Bold: "memorias inmortales",
      bio2Part2: "para atletas y aficionados, documentando el sudor, la gloria y el movimiento que definen la carrera de un deportista.",
      quote: "Basado en Portugal, trabajo en toda Europa, con especial énfasis en Portugal, Suiza, Reino Unido, Francia, España e Italia.",
      quoteEnd: "Donde haya alto rendimiento, allí estaré.",
      specialization: "Especialidades",
      cta: "¿VAMOS A CREAR TU PRÓXIMA MEMORIA?",
      badges: ["Fotógrafo de Eventos", "Fotografía Deportiva", "Creador de Conteúdo", "Social Media", "Marketing Deportivo", "Música en Vivo"],
    },
    services: {
      title: "Fotografía de Deportes y Eventos",
      location: "Con sede en Portugal | Disponible para viajar.",
      desc: "Fotografía comercial de alto impacto. Enfocada en registrar e inmortalizar los momentos decisivos de la acción técnica y la euforia humana, entregando poder y narrativa para su marca o equipo.",
      forWhom: "Para quién está indicado",
      features: "Servicios",
      deliveries: "Entregables típicos",
      prices: "Tarifas iniciales",
      cta: "Solicitar cobertura",
      globalCta: "CONTÁCTAME PARA HABLAR SOBRE TU PROYECTO",
      items: [
        { title: "Fotografía Deportiva", forWhom: ["Medios de comunicación", "Ligas deportivas", "Atletas individuales"], features: ["Cobertura en tiempo real", "Licencia de medios"], deliverables: ["Galería digital", "Fotos curadas para redes"], price: "€200 - €400" },
        { title: "Fotografía de Eventos", forWhom: ["Eventos Corporativos", "Galas de Premiación", "Conferências"], features: ["Documentación completa", "Fotos institucionales"], deliverables: ["Galería de RR.PP.", "Archivos de alta resolución"], price: "€400 (2h) - €1.200 (día completo)" },
        { title: "Trabajos Editoriales", forWhom: ["Revistas y Medios", "Reportajes sobre atletas"], features: ["Cobertura fotoperiodística", "Retratos dirigidos"], deliverables: ["Sesión fotográfica editorial", "Paquete de licencia prolongada"], price: "Bajo consulta" },
        { title: "Cobertura de Torneios", forWhom: ["Equipes esportivas", "Organizadores de Torneios"], features: ["Cobertura multi-campo", "Volumen fotográfico masivo"], deliverables: ["Galería grande de descarga", "Acceso a atletas"], price: "€400 - €1.200" },
      ],
    },
    contact: {
      title: "Vamos a Crear Juntos",
      subtitle: "Ya sea para una cobertura explosiva de eventos o retratos meticulosos, mi lente está lista para contar tu historia.",
      inquireTitle: "Consultar",
      inquireSub: "Completa los detalles a continuación y te responderé en menos de 48 horas.",
      form: {
        name: "Tu Nombre *",
        email: "Correo Electrónico *",
        date: "Fecha del Evento o Ubicación",
        message: "Cuéntame sobre tu proyecto *",
        send: "Enviar Solicitud",
        successTitle: "Mensaje Enviado",
        successDesc: "Gracias por contactarnos. Te responderé pronto para discutir tu visión.",
        another: "Enviar otro mensaje",
      },
      services: [
        { title: "Cobertura de Eventos", desc: "Capturando el calor, la emoción pura y cada momento irrepetível de tus eventos en vivo con ángulos cinematográficos impresionantes." },
        { title: "Retratos de Atletas", desc: "Retratos íntimos y poderosos en estudio o exteriores que destacan la resistencia, dedicación y personalidad del atleta." },
        { title: "Comercial & Marca", desc: "Fotografía institucional y publicitaria de alto nivel adaptada para elevar la narrativa y presencia de tu marca." },
      ],
    },
    blog: {
      title: "World Sports Hub",
      subtitle: "Donde el rendimiento se encuentra con la información.",
      categories: {
        football: "Fútbol",
        motorsport: "Motorsport",
        bouncing: "Bouncing & Action",
        mind: "Mind Sports",
      },
      filters: {
        all: "Todos",
        men: "Masculino",
        women: "Femenino",
        f1: "Fórmula 1",
        nba: "NBA",
        poker: "Poker",
      },
      rankings: {
        title: "World Rankings & Highlights",
        desc: "Destaque de las principales ligas mundiales.",
      },
      readMore: "Leer noticia completa",
      aggregated: "Noticias agregadas automáticamente de los principales portales deportivos mundiales.",
      loading: "Cargando feed...",
      noNews: "No se encontraron noticias para esta categoría.",
      source: "Fuente",
    },
    footer: {
      bio: "Fotografía de alto impacto capturando los momentos decisivos en el deporte, la acción y el ámbito comercial.",
      links: "Enlaces Rápidos",
      social: "Redes Sociales",
      devBy: "Desarrollado por",
      copy: "Todos los derechos reservados",
    },
    modal: {
      title: "Seleccionar Idioma",
      desc: "Elige tu idioma preferido para continuar explorando el portafolio.",
    },
    ui: {
      language: "Idioma",
      theme: "Tema",
    }
  },
  FR: {
    navbar: { work: "Travaux", about: "À propos", services: "Services", contact: "Contact", blog: "Actualités" },
    seo: {
      title: "Matthew Pinho | Photographie de Sport & Événements",
      description: "Capturer la haute performance et le récit athlétique à travers l'Europe. Spécialiste de la photographie de sport et d'événements commerciaux.",
    },
    hero: {
      titlePart1: "Capturer le",
      titlePart2: "Moment",
      titlePart3: "au cœur du mouvement",
      subtitle: "Poésie visuelle à travers un objectif cinématographique. Spécialisé dans la photographie haut de gamme et la capture de mouvements dynamiques.",
      portfolioBtn: "Voir le Portfolio",
      workBtn: "Travailler avec moi",
      scroll: "Défiler",
    },
    about: {
      badge: "Qui je suis & Mission",
      title: "Matthew Pinho : La perspective d'un athlète à travers l'objectif.",
      bio1: "Plus qu'un photographe, je suis un",
      bio1Bold: "athlète qui vit pour le sport",
      bio1End: ". J'ai combiné passion et savoir-faire pour capturer l'essence de la performance.",
      bio2Part1: "Mon travail se concentre sur la création de",
      bio2Bold: "souvenirs éternels",
      bio2Part2: "pour les athlètes et les fans, documentant la sueur, la gloire et le mouvement qui définissent une carrière sportive.",
      quote: "Basé au Portugal, j'interviens dans toute l'Europe, spécialisé au Portugal, Suisse, Royaume-Uni, France, Espagne et Italie.",
      quoteEnd: "Partout où il y a de la haute performance, je serai présent.",
      specialization: "Spécialisations",
      cta: "CRÉONS VOTRE PROCHAIN SOUVENIR ?",
      badges: ["Photographe d'événements", "Photographie sportive", "Créateur de contenu", "Médias sociaux", "Marketing sportif", "Musique live"],
    },
    services: {
      title: "Photographie de Sport & Événements",
      location: "Basé au Portugal | Disponible pour déplacements.",
      desc: "Photographie commerciale à fort impact. Axée sur l'enregistrement et l'immortalisation des moments décisifs de l'action et de l'euphorie humaine, apportant puissance et narration à votre marque ou équipe.",
      forWhom: "Pour qui c'est indiqué",
      features: "Services",
      deliveries: "Livrables typiques",
      prices: "Tarifs initiaux",
      cta: "Demander une couverture",
      globalCta: "CONTACTEZ-MOI POUR DISCUTER DE VOTRE PROJET",
      items: [
        { title: "Photographie Sportive", forWhom: ["Médias", "Ligues sportives", "Athlètes individuels"], features: ["Couverture en tempo réel", "Licences média"], deliverables: ["Galerie numérique", "Photos réseaux sociaux"], price: "€200 - €400" },
        { title: "Photographie d'Événements", forWhom: ["Événements d'entreprise", "Galas de remise de prix", "Conférences"], features: ["Documentation complète", "Photos institutionnelles"], deliverables: ["Galerie RP", "Fichiers haute résolution"], price: "€400 (2h) - €1.200 (journée complète)" },
        { title: "Travaux Éditoriaux", forWhom: ["Magazines & Médias", "Portraits d'athlètes"], features: ["Couverture photo-journalistique", "Portraits dirigés"], deliverables: ["Séance photo éditoriale", "Pack licence longue durée"], price: "Sur demande" },
        { title: "Couverture de Tournois", forWhom: ["Équipes sportives", "Organisateurs de tournois"], features: ["Couverture multi-terrains", "Volume photo massif"], deliverables: ["Grande galerie de téléchargement", "Accès aux athlètes"], price: "€400 - €1.200" },
      ],
    },
    contact: {
      title: "Créons ensemble",
      subtitle: "Que vous ayez besoin d'une couverture d'événement explosive ou de portraits méticuleux, mon objectif est prêt à raconter votre história.",
      inquireTitle: "Demander",
      inquireSub: "Remplissez les détails ci-dessous et je vous répondrai sous 48 heures.",
      form: {
        name: "Votre Nom *",
        email: "Adresse Email *",
        date: "Date de l'événement ou Lieu",
        message: "Parlez-moi de votre projet *",
        send: "Envoyer la demande",
        successTitle: "Message Envoyé",
        successDesc: "Merci de nous avoir contactés. Je reviendrai vers vous pour discuter de votre vision.",
        another: "Envoyer un autre message",
      },
      services: [
        { title: "Couverture d'Événements", desc: "Capturer la ferveur, l'émotion brute et chaque moment unique de vos événements en direct avec des angles cinématographiques percutants." },
        { title: "Portraits d'Athlètes", desc: "Portraits intimes et puissants en studio ou en extérieur mettant en avant la résilience et la personnalité de l'athlète." },
        { title: "Commercial & Marque", desc: "Photographie institutionnelle et publicitaire haut de gamme conçue pour élever le récit de votre marque." },
      ],
    },
    blog: {
      title: "World Sports Hub",
      subtitle: "Où la performance rencontre l'information.",
      categories: {
        football: "Football",
        motorsport: "Motorsport",
        bouncing: "Bouncing & Action",
        mind: "Mind Sports",
      },
      filters: {
        all: "Tous",
        men: "Masculin",
        women: "Féminin",
        f1: "Formule 1",
        nba: "NBA",
        poker: "Poker",
      },
      rankings: {
        title: "World Rankings & Highlights",
        desc: "Classements clés des championnats mondiaux.",
      },
      readMore: "Lire l'article complet",
      aggregated: "Actualités agrégées automatiquement des principaux portais sportifs mondiaux.",
      loading: "Chargement du flux...",
      noNews: "Aucune actualité trouvée pour cette catégorie.",
      source: "Source",
    },
    footer: {
      bio: "Photographie percutale capturant les moments décisifs dans le sport, l'action et le domaine commercial.",
      links: "Liens Rapides",
      social: "Réseaux Sociaux",
      devBy: "Développé par",
      copy: "Tous droits réservés",
    },
    modal: {
      title: "Choisir la Langue",
      desc: "Choisissez votre langue préférée para continuer à explorer le portfolio.",
    },
    ui: {
      language: "Langue",
      theme: "Thème",
    }
  },
};
